services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

    server:
        build:
            context: .
            dockerfile: Dockerfile.base
        ports:
            - 3000:3000
        command: sh -c "python3 -m prisma db push && fastapi dev src/main.py --host 0.0.0.0 --port 3000"
        volumes:
            - .:/app
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
